auth_enabled: false
server:
  http_listen_port: 3100
common:
  ring:
    instance_addr: localhost
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /loki/data
ingester:
  max_chunk_age: 1h
  chunk_target_size: 1048576
schema_config:
  configs:
    - from: 2020-10-10
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
storage_config:
  filesystem:
    directory: /loki/data/chunks
ruler:
  alertmanager_url: http://localhost:9093